"""
Module Name: snowflake_connector.py
 
Description:
This module provides functionality to execute SQL queries on a Snowflake database.
It handles the connection setup using environment variables, execution of SQL queries,
and returning results in JSON format. Errors are handled and returned as JSON strings
to ensure robustness.
"""
 
# ---------------------------------------------------------------------------
# SECTION: Imports
# ---------------------------------------------------------------------------
 
# Standard library imports
from typing import Dict, Any
import logging
import json
import os
import re
 
# Third-party imports
from dotenv import load_dotenv
import snowflake.connector
 
# ---------------------------------------------------------------------------
# SECTION: Logger Setup
# ---------------------------------------------------------------------------
 
# Get a logger instance for this module
logger = logging.getLogger(__name__)

# Load environment variables from .env for standalone usage as well.
load_dotenv()
 
# ---------------------------------------------------------------------------
# SECTION: SnowflakeConnector Class
# ---------------------------------------------------------------------------
 
class SnowflakeConnector:
    """
    A class to manage Snowflake database interactions, including connection
    setup, query execution, and result formatting.
    """
 
    def __init__(self):
        """
        Initialize the SnowflakeConnector instance and load environment variables.
        """
        # Retrieve environment variables
        self.connection_params: Dict[str, Any] = {
            "user": os.getenv("DB_USER"),
            "account": os.getenv("DB_HOST"),
            "warehouse": os.getenv('DB_WAREHOUSE'),
            "database": os.getenv("DB_NAME"),
            "role": os.getenv("DB_ROLE"),
            "password": os.getenv("DB_PASSWORD"),
        }

    def _validate_connection_params(self) -> str | None:
        """
        Validate required Snowflake connection params and return an error message if invalid.
        """
        required_fields = ["user", "account", "warehouse", "database", "role", "password"]
        missing_fields = [field for field in required_fields if not self.connection_params.get(field)]
        if missing_fields:
            return f"Missing required Snowflake env vars for: {', '.join(missing_fields)}"

        account = str(self.connection_params.get("account", "")).strip()
        if "/" in account:
            return (
                "Invalid Snowflake account format in DB_HOST. "
                "Use account identifier format like '<account_locator>.<region>.<cloud>' "
                "(example: 'cjzlrgx.ap-south-1.aws') and not values with '/'."
            )
        return None
 
    def _clean_query(self, query: str) -> str:
        """
        Clean unwanted double quotes from an LLM-generated SQL query while keeping
        double quotes around identifiers with special characters.
 
        Args:
            query (str): The SQL query generated by the LLM.
 
        Returns:
            str: The cleaned and executable SQL query.
        """
        cleaned_query = re.sub(r'\"([a-zA-Z0-9_]+)\"', r'\1', query)
        cleaned_query = re.sub(r'\s+', ' ', cleaned_query).strip()
        return cleaned_query
 
    def execute_query(self, sql_query: str) -> str:
        """
        Execute a SQL query on Snowflake and return the result as a JSON string.
 
        Args:
            sql_query (str): The SQL query to execute.
 
        Returns:
            str: A JSON string representing the query result, or an error message if
            the query execution fails.
        """
        conn = None
        cur = None
 
        try:
            validation_error = self._validate_connection_params()
            if validation_error:
                logger.error(validation_error)
                return json.dumps({"error": validation_error})

            # Establish a connection to Snowflake
            conn = snowflake.connector.connect(**self.connection_params)
            warehouse_name = self.connection_params['warehouse']
 
            # Create a cursor object
            cur = conn.cursor()
            cur.execute("USE WAREHOUSE " + warehouse_name)
 
            # Clean the query and ensure we don't fetch too much data
            cleaned_query = self._clean_query(sql_query)
            if not re.search(r"\blimit\b", cleaned_query.lower()):
                cleaned_query = cleaned_query.rstrip(';') + ' LIMIT 10'

            logger.info(f"Executing Snowflake query: {cleaned_query}")
            cur.execute(cleaned_query)
 
            # Fetch and format the results
            column_names = [metadata.name for metadata in cur.description]
            rows = cur.fetchall()
            json_data = json.dumps([
                {key: str(value) for key, value in zip(column_names, row)}
                for row in rows
            ])
            return json_data
 
        except snowflake.connector.errors.ProgrammingError as pe:
            logger.error(pe)
            return json.dumps({"error": str(pe)})
 
        except snowflake.connector.errors.DatabaseError as de:
            logger.error(de)
            return json.dumps({"error": f"Snowflake Database Error: {de}"})
 
        except Exception as e:
            logger.error(e)
            return json.dumps({"error": f"An unexpected error occurred: {e}"})
 
        finally:
            # Ensure the cursor is closed
            if cur:
                try:
                    cur.close()
                except Exception:
                    pass
 
            # Ensure the connection is closed
            if conn:
                try:
                    conn.close()
                except Exception:
                    pass
 
# ---------------------------------------------------------------------------
# END OF MODULE
# ---------------------------------------------------------------------------