"""
Module Name: q_and_a_agent.py

Description:
This module contains the implementation of a Q&A agent using LangChain components. 
It defines the pipeline for generating final answers based on user input, previous 
agent responses, and conversation history. The module also includes the Pydantic 
model for structuring the Q&A response.

"""

# ----------------------------------------------------------------------------- 
# SECTION: Imports
# ----------------------------------------------------------------------------- 

# Third-party imports
from langchain_community.callbacks import get_openai_callback
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.pydantic_v1 import BaseModel, Field
import logging

# Local application imports
from models.azure_openai_model import model
from utils.helper_functions import load_prompt

# Logger
logger = logging.getLogger(__name__)

# ----------------------------------------------------------------------------- 
# SECTION: Load Prompt
# ----------------------------------------------------------------------------- 

# Load the Q&A system prompt from a file
q_and_a_system_text = load_prompt("prompts/core_engine/q_and_a_system_prompt.txt")

# Create chat prompt template
q_and_a_prompt = ChatPromptTemplate.from_messages(
    [("system", q_and_a_system_text)]
)

# ----------------------------------------------------------------------------- 
# SECTION: Define Models and Chain
# ----------------------------------------------------------------------------- 

class QA(BaseModel):
    """
    Pydantic model for the Q&A response.

    Attributes:
        q_and_a (str): Final answer to the question.
    """
    q_and_a: str = Field(description="Final answer to the question")


# Create the output parser
parser = JsonOutputParser(pydantic_object=QA)

# Define the Q&A chain
q_and_a_chain = q_and_a_prompt | model | parser

# ----------------------------------------------------------------------------- 
# SECTION: Q&A Agent Function
# ----------------------------------------------------------------------------- 

def q_and_a_agent(user_input: str, agents_response: str, conversation_history: str) -> tuple:
    """
    Generate a final answer using the Q&A agent.

    This function processes the user's question, other agent responses, and conversation 
    history to generate a final answer using the Q&A agent chain.

    Args:
        user_input (str): The user's input question.
        agents_response (str): The response from other agents.
        conversation_history (str): The conversation history.

    Returns:
        tuple: A tuple containing:
            - str: The final answer to the user's question.
            - int: The number of input tokens used by the AI model.
            - int: The number of output tokens generated by the AI model.
    """
    # Truncate agents_response if too long to avoid OpenAI message length limit
    max_length = 5000000  # ~5MB limit to be safe
    if isinstance(agents_response, str) and len(agents_response) > max_length:
        agents_response = agents_response[:max_length] + "\n\n[Response truncated due to length]"
    elif isinstance(agents_response, (list, dict)):
        agents_response_str = str(agents_response)
        if len(agents_response_str) > max_length:
            agents_response = agents_response_str[:max_length] + "\n\n[Response truncated due to length]"

    try:
        with get_openai_callback() as cb:
            ai_response = q_and_a_chain.invoke({
                "user_input": user_input,
                "agents_response": agents_response,
                "conversation_history": conversation_history
            })
            input_tokens_count = cb.prompt_tokens
            output_tokens_count = cb.completion_tokens
            if isinstance(ai_response, dict) and "q_and_a" in ai_response:
                return ai_response["q_and_a"], input_tokens_count, output_tokens_count
            if hasattr(ai_response, "get") and ai_response.get("q_and_a"):
                return ai_response.get("q_and_a"), input_tokens_count, output_tokens_count

        return "Sorry, I couldn't generate a response right now.", input_tokens_count, output_tokens_count
    except Exception as e:
        logger.error("Error in q_and_a_agent: %s", str(e))
        return "Sorry, I couldn't generate a response right now.\nDetails: %s" % str(e), 0, 0


# ----------------------------------------------------------------------------- 
# END OF MODULE
# ----------------------------------------------------------------------------- 
