"""
Module Name: generic_conversation_agent.py

Description:
This module provides functionality for a generic conversation agent that leverages 
LLM-based responses. It defines the conversation pipeline, including loading system prompts,
and handling user input to produce AI-driven responses. The module also includes utility 
functions for token counting and input text extraction.

"""

# -----------------------------------------------------------------------------
# SECTION: Imports
# -----------------------------------------------------------------------------

# Standard library imports
from typing import Union, Dict, List

# Third-party imports
from langchain.agents import AgentExecutor, create_openai_tools_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
import tiktoken

# Local application imports
from models.azure_openai_model import model
from utils.helper_functions import load_prompt

# -----------------------------------------------------------------------------
# SECTION: Load Prompts
# -----------------------------------------------------------------------------

# Load the system generic_conversation prompt from a file
generic_conversation_system_text = load_prompt("prompts/generic_conversation/generic_conversation_system_prompt.txt")

# Create chat prompt template
generic_conversation_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", generic_conversation_system_text),
        MessagesPlaceholder(variable_name="agent_scratchpad")
    ]
)

# Create an agent using the LLM without external tools
llm_with_tools = model  # Direct binding to the model without additional tools
generic_conversation_agent = create_openai_tools_agent(
    llm_with_tools,
    tools=[],  # No external tools are used initially
    prompt=generic_conversation_prompt
)

# Agent executor with placeholder tools
agent_executor = AgentExecutor(agent=generic_conversation_agent, tools=[])

# -----------------------------------------------------------------------------
# SECTION: Utility Functions
# -----------------------------------------------------------------------------

def num_tokens_from_string(string: str, encoding_name: str) -> int:
    """
    Calculate the number of tokens in a string based on the specified encoding.

    Args:
        string (str): The input string to encode.
        encoding_name (str): The name of the encoding to use.

    Returns:
        int: The number of tokens in the encoded string.
    """
    encoding = tiktoken.get_encoding(encoding_name)
    return len(encoding.encode(string))

def get_input_text(function_params: Union[Dict[str, str], List[str]]) -> str:
    """
    Extract input text from function parameters.

    Args:
        function_params (Union[Dict[str, str], List[str]]): Either a dictionary with 
        an 'input_text' key or a list with input text.

    Returns:
        str: Extracted input text.

    Raises:
        ValueError: If invalid arguments are passed.
    """
    if isinstance(function_params, dict):
        return function_params.get('input_text', '')
    elif isinstance(function_params, list) and function_params:
        return function_params[0]
    elif isinstance(function_params, str) and function_params:
        return function_params
    raise ValueError("Invalid arguments passed to the generic_conversation_agent function.")

# -----------------------------------------------------------------------------
# SECTION: Main Function
# -----------------------------------------------------------------------------

def generic_conversation_agent(function_params: Union[Dict[str, str], List[str]], tools: List[Dict] = None) -> tuple:
    """
    Function for the generic conversation agent.

    Args:
        function_params (Union[Dict[str, str], List[str]]): Either a dictionary with 
        an 'input_text' key or a list with input text.
        tools (List[Dict], optional): A list of tools available for the agent. Defaults to None.

    Returns:
        tuple: A tuple containing:
            - str: Response generated by the generic conversation agent.
            - int: Number of input tokens used.
            - int: Number of output tokens generated.

    Raises:
        ValueError: If invalid arguments are passed to the function or tools are missing.
    """
    if tools is None or not tools:
        return {"error": "Invalid 'tools': empty array. Please provide at least one tool."}, 0, 0

    input_text = get_input_text(function_params)

    try:
        ai_response = agent_executor.invoke({"user_input": input_text, "tools": tools})

        prompt_as_string = generic_conversation_prompt.format(
            user_input=input_text,
            agent_scratchpad=[]
        )

        input_tokens_count = num_tokens_from_string(prompt_as_string, "cl100k_base")
        output_tokens_count = num_tokens_from_string(ai_response['output'], "cl100k_base")

        return ai_response['output'], input_tokens_count, output_tokens_count

    except Exception as e:
        return {"error": f"Agent failed with error: {str(e)}"}, 0, 0

# -----------------------------------------------------------------------------
# END OF MODULE
# -----------------------------------------------------------------------------
