"""
 
Module Name: bigquery_connector.py
 
Description:
This module provides functionality to execute SQL queries on a Google BigQuery database.
It handles the connection setup using environment variables, execution of SQL queries,
and returning results in JSON format. Errors are handled and returned as JSON strings
to ensure robustness.
 
Note:
    - This uses a single dataset name for all queries.
    - The dataset name is fetched from the .env file.
 
"""
 
# -----------------------------------------------------------------------------
# SECTION: Imports
# -----------------------------------------------------------------------------
 
# Standard library imports
from typing import Dict, Any
import json
import os
import re
import datetime
 
from dotenv import load_dotenv
import snowflake.connector
 
# -----------------------------------------------------------------------------
# SECTION: Environment Variable Loading
# -----------------------------------------------------------------------------
 
# Load environment variables from the .env file
load_dotenv()
 

# Retrieve Snowflake environment variables
SNOWFLAKE_USER = os.getenv("SNOWFLAKE_USER")
SNOWFLAKE_PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")
SNOWFLAKE_ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE")
SNOWFLAKE_SCHEMA = os.getenv("SNOWFLAKE_SCHEMA")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE")
 
# -----------------------------------------------------------------------------
# SECTION: Clean unwanted Double Quotes from LLM-Generated SQL Queries
# -----------------------------------------------------------------------------
 
def clean_snowflake_query(query: str) -> str:
    """
    Cleans unwanted double quotes from an LLM-generated SQL query while keeping
    double quotes around identifiers with special characters.
    Args:
        query (str): The SQL query generated by the LLM.
    Returns:
        str: The cleaned and executable SQL query.
    """
    cleaned_query = re.sub(r'\"([a-zA-Z0-9_]+)\"', r'\1', query)
    cleaned_query = re.sub(r'\s+', ' ', cleaned_query)
    cleaned_query = cleaned_query.strip()
    return cleaned_query
 
# -----------------------------------------------------------------------------
# SECTION: Helper for JSON Serialization
# -----------------------------------------------------------------------------
 
def serialize_row(row: dict) -> dict:
    """
    Converts date and datetime objects in a row to ISO format strings for JSON serialization.
    """
    return {
        k: (v.isoformat() if isinstance(v, (datetime.date, datetime.datetime)) else v)
        for k, v in row.items()
    }
 
# -----------------------------------------------------------------------------
# SECTION: Executing SQL query on BigQuery
# -----------------------------------------------------------------------------
 
def get_snowflake_connection():
    return snowflake.connector.connect(
        user=SNOWFLAKE_USER,
        password=SNOWFLAKE_PASSWORD,
        account=SNOWFLAKE_ACCOUNT,
        warehouse=SNOWFLAKE_WAREHOUSE,
        database=SNOWFLAKE_DATABASE,
        schema=SNOWFLAKE_SCHEMA
    )

def execute_snowflake_query(sql_query: str, params=None) -> str:
    """
    Executes a SQL query on Snowflake and returns the result as a JSON string.
    """
    try:
        conn = get_snowflake_connection()
        cur = conn.cursor()
        cleaned_query = clean_snowflake_query(sql_query)
        cur.execute(cleaned_query, params or [])
        # Fetch column names
        column_names = [desc[0] for desc in cur.description] if cur.description else []
        rows = [serialize_row(dict(zip(column_names, row))) for row in cur.fetchall()] if column_names else []
        cur.close()
        conn.close()

        if not rows:
            return json.dumps({
                "status": "no_data",
                "message": "No data available for the requested period.",
                "data": []
            })
        else:
            return json.dumps({
                "status": "success",
                "data": rows
            })
    except Exception as e:
        return json.dumps({
            "error": str(e)
        })