"""
Module Name: core_engine_workflow_graph.py
 
Description:
This module implements a custom workflow graph for the Solenis-bot system, integrating
various agents and maintaining conversation history. The graph coordinates task execution
among agents, resolves dependencies, and tracks token usage during the conversation.
Adapted for Snowflake in RE_v2.
"""
 
# -----------------------------------------------------------------------------
# SECTION: Imports
# -----------------------------------------------------------------------------
 
# Standard library imports
from typing import Any, Dict
import logging
import os
import json
import re
 
# Local application imports
from agents.core_engine_agents.dependency_resolver_agent import dependency_resolver
from agents.core_engine_agents.conversation_summary_agent import conversation_summary_agent
from agents.core_engine_agents.human_agent import human_agent
from agents.core_engine_agents.supervisor_agent import supervisor_agent
from agents.generic_conversation_agent import generic_conversation_agent
from agents.graph_and_summary_agent import graph_and_summary_agent
from agents.snowflake_agents.snowflake_query_agent import snowflake_agent, generate_table_metadata_from_file
from connectors.snowflake_connector_v1 import execute_snowflake_query
from agents.core_engine_agents.insightful_question_agent import generate_related_questions
from utils.input_analyzer import analyze_user_input, generate_clarification_question, is_direct_metric_query
 
# Third-party imports
from dotenv import load_dotenv
 
# -----------------------------------------------------------------------------
# SECTION: Environment Setup
# -----------------------------------------------------------------------------
 
# Load environment variables from .env file
load_dotenv()
 
# Maxium length of conversation history after which it would be summarized
MAXIMUM_CONVERSATION_HISTORY_LENGTH = int(os.getenv("MAXIMUM_CONVERSATION_HISTORY_LENGTH", "5"))
 
# -----------------------------------------------------------------------------
# SECTION: Task Executor Implementation
# -----------------------------------------------------------------------------
 
def execute_tasks(ai_tasks_list, assumptions):
    """
    Executes the list of tasks generated by the supervisor agent.
    Args:
        ai_tasks_list (list): List of tasks generated by the supervisor agent.
    Returns:
        tuple: (task_outputs, total_input_tokens_count, total_output_tokens_count, generated_snowflake_queries_list, requires_clarification)
    """
    task_outputs = []  # List to store task outputs with sequence IDs
    total_input_tokens_count = 0
    total_output_tokens_count = 0
    generated_snowflake_queries_list = []
    requires_clarification = False
 
    for i, task in enumerate(ai_tasks_list, start=1):
        function_name = task["function_name"]
        function_params = task["function_params"]
        task_id = i
 
        print(f"Executing Task ID: {task_id}, Function Name: {function_name}, Params: {function_params}")
        if function_name == "human_agent":
            requires_clarification = True
            print("Human agent detected - clarification required")

        # Handle the list vs dict/string mismatch
        if isinstance(function_params, list) and len(function_params) == 1:
            params_to_pass = function_params[0]
        else:
            params_to_pass = function_params
 
        # Inject interpretation into Snowflake input_text
        if function_name == "snowflake_agent" and isinstance(params_to_pass, str):
            if assumptions and "(Interpretation:" not in params_to_pass:
                params_to_pass = params_to_pass + " (Interpretation: " + "; ".join(assumptions) + ")"
 
        func = globals().get(function_name)
        if not func:
            print(f"Function '{function_name}' not found.")
            continue
 
        try:
            # Most agents return (output, input_tokens, output_tokens) or (q, r, input_tokens, output_tokens)
            result = func(params_to_pass)
            
            if isinstance(result, tuple):
                if function_name == "snowflake_agent":
                    # snowflake_agent returns (query, result, in_tokens, out_tokens)
                    query, output, in_tokens, out_tokens = result
                    generated_snowflake_queries_list.append(query)
                    function_output = output
                else:
                    # Generic case (output, in_tokens, out_tokens)
                    function_output, in_tokens, out_tokens = result
                
                total_input_tokens_count += (in_tokens or 0)
                total_output_tokens_count += (out_tokens or 0)
            else:
                function_output = result

            print(f"Function Output for {function_name}:", function_output)
 
            if function_output:
                task_outputs.append({
                    "task_id": task_id,
                    "function_name": function_name,
                    "output": function_output
                })
            else:
                print(f"No output generated for task {task_id} ({function_name}).")
 
        except Exception as e:
            print(f"Error in {function_name}: {str(e)}")
 
    return task_outputs, total_input_tokens_count, total_output_tokens_count, generated_snowflake_queries_list, requires_clarification
 
# -----------------------------------------------------------------------------
# SECTION: Workflow Graph Implementation
# -----------------------------------------------------------------------------
 
def _extract_original_query(conversation_history: list) -> str | None:
    """
    Find the most recent original query that a clarification was asking about.
    """
    if not isinstance(conversation_history, list):
        return None
    for entry in reversed(conversation_history):
        if isinstance(entry, dict) and entry.get("original_query"):
            return entry.get("original_query")
    for entry in reversed(conversation_history):
        if isinstance(entry, dict) and entry.get("role", "").lower() == "user":
            return entry.get("user_input")
    return None
 
def solenis_bot_workflow_graph(user_input: str, conversation_history: list) -> Dict[str, Any]:
    """
    Execute the Solenis-bot workflow graph, managing conversation history and invoking various agents.
    """
    total_input_tokens_count = 0
    total_output_tokens_count = 0
 
    conversation = {
        "conversation_history": [],
        "present_conversation": []
    }
    # conversation["present_conversation"].append({"user_input": user_input})
 
    # Pre-process input
    print(f"Workflow: Analyzing input: {user_input}")
    input_analysis = analyze_user_input(user_input)
    print(f"Workflow: Analysis complete: {input_analysis}")
 
    # EARLY EXIT: clarification required
    if input_analysis.get("requires_clarification", False):
        print("Workflow: Clarification required.")
        clarification_question = generate_clarification_question(input_analysis, user_input)
        return {
            "conversation": {
                "conversation_history": conversation_history,
                "present_conversation": [{
                    "user_input": user_input,
                    "clarification_question": clarification_question,
                    "requires_clarification": True,
                    "original_query": user_input
                }]
            },
            "requires_clarification": True,
            "clarification_question": clarification_question,
            "original_query": user_input,
            "input_tokens_count": 0,
            "output_tokens_count": 0
        }
 
    # Build Interpretation
    user_input_aug = user_input
    assumptions = input_analysis.get("assumptions", [])
    if assumptions:
        user_input_aug = f"{user_input} (Interpretation: " + "; ".join(assumptions) + ")"
 
    # Clarification response handling
    if isinstance(conversation_history, list) and len(conversation_history) > 0:
        clarity_words = [
            "department", "dept", "commercial bu", "commercial business unit", "cp", "bu",
            "business unit", "client partner", "delivery partner", "opportunity owner",
            "account", "account name", "account owner",
        ]
        user_input_lower = user_input.lower()
        has_clarity_word = any(re.search(r'\b' + re.escape(w) + r'\b', user_input_lower) for w in clarity_words)
        is_short = len(user_input.split()) < 10
        is_clarification_followup = False
        for entry in reversed(conversation_history):
            if isinstance(entry, dict) and entry.get("role", "").lower() == "assistant":
                entry_type = str(entry.get("type", "")).lower()
                entry_text = str(entry.get("user_input") or entry.get("content") or "").lower()
                if "clarification" in entry_type or "clarify" in entry_text:
                    is_clarification_followup = True
                break
       
        if not is_direct_metric_query(user_input):
            if is_short and has_clarity_word and is_clarification_followup:
                original_query = _extract_original_query(conversation_history)
                if original_query:
                    if "business unit" in user_input_lower or "commercial bu" in user_input_lower:
                        enhanced_query = f"{original_query} (referring to Commercial Business Unit)"
                    elif "department" in user_input_lower:
                        enhanced_query = f"{original_query} (referring to Department)"
                    else:
                        enhanced_query = original_query
                    user_input_aug = enhanced_query
 
    print("\nInvoking Supervisor Agent\n")
 
    # Step 1: Generate tasks using the supervisor agent
    supervisor_response, in_tokens, out_tokens = supervisor_agent(
        user_input=user_input_aug,
        conversation_history=conversation_history
    )
    print(f"Workflow: Supervisor response: {supervisor_response}")
    total_input_tokens_count += in_tokens
    total_output_tokens_count += out_tokens
 
    if isinstance(supervisor_response, dict):
        ai_tasks_list = supervisor_response.get("tasks", [])
        if not ai_tasks_list and "error" in supervisor_response:
             raise ValueError(f"Supervisor Agent error: {supervisor_response['error']}")
    elif isinstance(supervisor_response, list):
        ai_tasks_list = supervisor_response
    else:
        print(f"Workflow: Unexpected supervisor response type: {type(supervisor_response)}")
        ai_tasks_list = []
 
    # EARLY EXIT: Supervisor detected incoherent input
    if any(task.get("function_name") == "human_agent" for task in ai_tasks_list):
        incoherent_message = "Please ask a clear business question so I can help."
        return {
            "conversation": {
                "conversation_history": conversation_history,
                "present_conversation": [{
                    "user_input": user_input,
                    "clarification_question": incoherent_message,
                    "requires_clarification": True,
                    "original_query": user_input
                }]
            },
            "requires_clarification": True,
            "clarification_question": incoherent_message,
            "original_query": user_input,
            "input_tokens_count": total_input_tokens_count,
            "output_tokens_count": total_output_tokens_count
        }
 
    # Step 2: Execute tasks
    task_outputs, in_tokens, out_tokens, generated_snowflake_query, requires_clarification = execute_tasks(ai_tasks_list, assumptions)
    total_input_tokens_count += in_tokens
    total_output_tokens_count += out_tokens
 
    # Handle clarification logic from task output (e.g. if snowflake agent fails and needs context)
    if not task_outputs or requires_clarification:
        # Simplified for now
        pass

    # Load metadata for related questions
    metadata_file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "metadata.txt")
    table_metadata = generate_table_metadata_from_file(metadata_file_path)
 
    # Step 3: Graph and summary agent
    graph_and_summary_agent_output, in_tokens, out_tokens = graph_and_summary_agent(
        user_input=user_input_aug,
        other_agents_response=task_outputs
    )
    total_input_tokens_count += in_tokens
    total_output_tokens_count += out_tokens
 
    # Step 4: Generate follow-up questions
    insightful_questions, in_tokens, out_tokens = generate_related_questions(
        user_input=user_input,
        llm_response=str(task_outputs[0]["output"]) if task_outputs else "",
        table_metadata=table_metadata
    )
    total_input_tokens_count += in_tokens
    total_output_tokens_count += out_tokens
 
    conversation["present_conversation"].append({
        "user_input": user_input,
        "snowflake_agent": task_outputs[0]["output"] if task_outputs else {},
        "graph_and_summary_agent": graph_and_summary_agent_output,
        "insightful_questions": insightful_questions
    })
 
    return {
        "conversation": {
            "conversation_history": conversation_history,
            "present_conversation": conversation["present_conversation"]
        },
        "generated_snowflake_query": generated_snowflake_query,
        "input_tokens_count": total_input_tokens_count,
        "output_tokens_count": total_output_tokens_count
    }
