"""
Module Name: core_engine_workflow_graph.py

Description:
This module implements a custom workflow graph for the Ask Ellis system, integrating
various agents and maintaining conversation history. The graph coordinates task execution
among agents, resolves dependencies, and tracks token usage during the conversation.

"""

# -----------------------------------------------------------------------------
# SECTION: Imports
# ----------------------------------------------------------------------------- 

# Standard library imports
from typing import Any, Dict
import logging
import os

# Local application imports
from agents.core_engine_agents.dependency_resolver_agent import dependency_resolver
from agents.core_engine_agents.conversation_summary_agent import conversation_summary_agent
from agents.core_engine_agents.human_agent import human_agent
from agents.core_engine_agents.supervisor_agent import supervisor_agent
from agents.core_engine_agents.q_and_a_agent import q_and_a_agent
from agents.generic_conversation_agent import generic_conversation_agent
from agents.snowflake_agents.snowflake_query_agent import snowflake_agent
from connectors.snowflake_connector_v1 import clean_snowflake_query

# Third-party imports
from dotenv import load_dotenv

# -----------------------------------------------------------------------------
# SECTION: Logger Setup
# ----------------------------------------------------------------------------- 

# Get a logger instance for this module
logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------------
# SECTION: Environment Setup
# ----------------------------------------------------------------------------- 

# Load environment variables from .env file
load_dotenv()

# Maxium length of conversation history after which it will be summarized
MAXIMUM_CONVERSATION_HISTORY_LENGTH = int(os.getenv("MAXIMUM_CONVERSATION_HISTORY_LENGTH"))

# -----------------------------------------------------------------------------
# SECTION: Task Executor Implementation
# ----------------------------------------------------------------------------- 

def _trim_conversation_history(conversation_history: Any, max_messages: int = 8) -> list:
    """Trim conversation history to the last N messages and compact fields."""
    if not isinstance(conversation_history, list):
        return []
    trimmed = conversation_history[-max_messages:]
    normalized = []
    for item in trimmed:
        if isinstance(item, dict):
            normalized.append({
                "user_input": item.get("user_input") or item.get("content") or "", 
                "role": item.get("role", "user"),
                "type": item.get("type", "text")
            })
        else:
            normalized.append({"user_input": str(item), "role": "user", "type": "text"})
    return normalized


def execute_tasks(ai_tasks_list):
    """
    Executes the list of tasks generated by the supervisor agent, handles dependency resolution,
    and updates task outputs and token counts.
    Args:
        ai_tasks_list (list): List of tasks generated by the supervisor agent.
    Returns:
        tuple: (task_outputs, total_input_tokens_count, total_output_tokens_count, generated_snowflake_queries_list)
    """
    task_outputs = []  # List to store task outputs with sequence IDs
    total_input_tokens_count = 0
    total_output_tokens_count = 0
    generated_snowflake_queries_list = []

    for i, task in enumerate(ai_tasks_list, start=1):  # Start sequence from 1
        function_name = task["function_name"]
        function_params = task["function_params"]
        task_id = i  # Use sequence number as task ID

        # Resolve dependencies if any
        if task.get("depends_on"):
            dependent_task_output = task_outputs[int(task["depends_on"]) - 1]["output"]
            next_task_info = {"function_params": function_params}
            function_params, input_tokens_count, output_tokens_count = dependency_resolver(
                dependent_task_output,
                next_task_info
            )
            total_input_tokens_count += input_tokens_count
            total_output_tokens_count += output_tokens_count
            logger.info("Dependency Resolver Output: %s", function_params)


        func = globals().get(function_name)

        # --- Patch: Ensure snowflake_agent gets a string, not a dict ---
        call_params = function_params
        if function_name == "snowflake_agent":
            # If function_params is a dict with a single string value, extract it
            if isinstance(function_params, dict):
                # Try to extract the first value
                if len(function_params) == 1:
                    call_params = next(iter(function_params.values()))
                else:
                    # If dict has more than one key, fallback to str()
                    call_params = str(function_params)
            elif isinstance(function_params, list) and len(function_params) == 1:
                call_params = function_params[0]

        scratchpad = None  # Default to None to handle different types of outputs
        if func:
            try:
                function_output = func(call_params)

                # Unpack the function output
                if isinstance(function_output, tuple) and len(function_output) == 4:
                    generated_snowflake_query, scratchpad, input_tokens_count, output_tokens_count = function_output
                    # Clean the Snowflake query before storing it
                    if isinstance(generated_snowflake_query, str) and generated_snowflake_query:
                        generated_snowflake_query = clean_snowflake_query(generated_snowflake_query)
                    generated_snowflake_queries_list.append(generated_snowflake_query)
                else:
                    scratchpad, input_tokens_count, output_tokens_count = function_output

                total_input_tokens_count += input_tokens_count
                total_output_tokens_count += output_tokens_count

            except Exception as e:
                scratchpad = f"Error in {function_name}: {str(e)}"
                logger.error(f"Error executing {function_name}: {e}")
        else:
            scratchpad = f"Function '{function_name}' not found."
            logger.error(f"Function '{function_name}' not found in the global namespace.")

        # Only store task output if it is non-empty
        if scratchpad not in (None, "", [], {}, ()) and bool(scratchpad):
            task_outputs.append({
                "task_id": task_id,
                "function_name": function_name,
                "output": scratchpad
            })

            print("\n")
            print("#" * 50)
            print(f"Task ID = {task_id}, Agent = {function_name}")
            print("Agent Output = ")
            print(scratchpad)
            print("#" * 50)
            print("\n")

    return task_outputs, total_input_tokens_count, total_output_tokens_count, generated_snowflake_queries_list

# -----------------------------------------------------------------------------
# SECTION: Workflow Graph Implementation
# ----------------------------------------------------------------------------- 

def ask_ellis_workflow_graph(user_input: str, conversation_history: Any) -> Dict[str, Any]:
    """
    Execute the Ask Ellis workflow graph, managing conversation history and invoking various agents.

    Includes retry logic to handle unsatisfactory responses by rerouting tasks through the supervisor with adjustments.

    Args:
        user_input (str): The user's input query.
        conversation_history (Any): The history of the conversation.

    Returns:
        Dict[str, Any]: A dictionary containing the conversation details, total input tokens,
                        and total output tokens used during the execution.
    """

    try:
        # Initialize token counts and retry counters
        total_input_tokens_count = 0
        total_output_tokens_count = 0

        # Initialize conversation and task outputs
        # Trim conversation history before processing to avoid token overflow
        trimmed_conversation_history = _trim_conversation_history(conversation_history, max_messages=8)
        conversation = {
            "conversation_history": trimmed_conversation_history,
            "present_conversation": []
        }
        logger.info("ask_ellis_workflow_graph: user_input=%s history_length=%s", user_input, len(trimmed_conversation_history))
        conversation["present_conversation"].append({"user_input": user_input})

        print("\n")
        print('*' * 50)
        print("Invoking Supervisor Agent")
        print('*' * 50)
        print("\n")

        # Step 1: Generate tasks using the supervisor agent, including retry context
        ai_tasks_list, input_tokens_count, output_tokens_count = supervisor_agent(
            user_input,
            trimmed_conversation_history,
            retry_context=[]  # Pass feedback on what went wrong in previous attempts
        )
        total_input_tokens_count += input_tokens_count
        total_output_tokens_count += output_tokens_count

        # Guard against supervisor failures (e.g., OpenAI auth/timeout) returning error dict
        if isinstance(ai_tasks_list, dict) and ai_tasks_list.get("error"):
            raise RuntimeError(f"Supervisor error: {ai_tasks_list.get('error')}")

        print('\n')
        print('*' * 50)
        print("Supervisor Agent Tasks List")
        print(ai_tasks_list)
        print('*' * 50)
        print('\n')

        logger.info("Supervisor Agent Output: %s", ai_tasks_list)

        # Step 2: Execute tasks using the execute_tasks function
        task_outputs, input_tokens_count, output_tokens_count, generated_snowflake_queries_list = execute_tasks(ai_tasks_list)
        total_input_tokens_count += input_tokens_count
        total_output_tokens_count += output_tokens_count

        # Append task outputs to the present conversation
        conversation["present_conversation"].extend(
            [{task["function_name"]: task["output"]} for task in task_outputs]
        )

        print('\n')
        print('*' * 50)
        print("Invoking Q&A Agent")
        print('*' * 50)
        print('\n')

        # Final call to Q&A agent with agents' responses
        ellis_response, input_tokens_count, output_tokens_count = q_and_a_agent(
            user_input=user_input,
            agents_response=task_outputs,
            conversation_history=trimmed_conversation_history
        )
        total_input_tokens_count += input_tokens_count
        total_output_tokens_count += output_tokens_count
        conversation["present_conversation"].append({"ellis_response": ellis_response})

        # Additional step to handle conversation history if it exceeds max length
        if len(conversation["conversation_history"]) > MAXIMUM_CONVERSATION_HISTORY_LENGTH:
            conversation_summary, input_tokens_count, output_tokens_count = conversation_summary_agent(
                conversation_history=conversation["conversation_history"]
            )
            total_input_tokens_count += input_tokens_count
            total_output_tokens_count += output_tokens_count
            conversation["conversation_history"].clear()
            conversation["conversation_history"].append({"conversation_summary": conversation_summary})

        conversation["conversation_history"].append(conversation["present_conversation"])

        # Return final conversation details and token counts
        return {
            "conversation": conversation,
            "generated_snowflake_query": generated_snowflake_queries_list,
            "input_tokens_count": total_input_tokens_count,
            "output_tokens_count": total_output_tokens_count
        }

    except Exception as e:
        logger.exception("Error in ask_ellis_workflow_graph: %s", e)
        return {
            "conversation": {
                "conversation_history": trimmed_conversation_history if 'trimmed_conversation_history' in locals() else [],
                "present_conversation": [{"user_input": user_input, "error": str(e)}],
                "error": str(e)
            },
            "generated_snowflake_query": [],
            "input_tokens_count": total_input_tokens_count if 'total_input_tokens_count' in locals() else 0,
            "output_tokens_count": total_output_tokens_count if 'total_output_tokens_count' in locals() else 0,
            "error": "ask_ellis_workflow_graph failed: %s" % str(e)
        }

# -----------------------------------------------------------------------------
# END OF MODULE
# ----------------------------------------------------------------------------- 
