"""
Module Name: core_engine_workflow_graph.py

Description:
This module implements a custom workflow graph for the Ask Ellis system, integrating
various agents and maintaining conversation history. The graph coordinates task execution
among agents, resolves dependencies, and tracks token usage during the conversation.

"""

# -----------------------------------------------------------------------------
# SECTION: Imports
# ----------------------------------------------------------------------------- 

# Standard library imports
from typing import Any, Dict, Optional
import json
import logging
import os
import re

# Local application imports
from agents.core_engine_agents.dependency_resolver_agent import dependency_resolver
from agents.core_engine_agents.conversation_summary_agent import conversation_summary_agent
from agents.core_engine_agents.human_agent import human_agent
from agents.core_engine_agents.supervisor_agent import supervisor_agent
from agents.core_engine_agents.q_and_a_agent import q_and_a_agent
from agents.generic_conversation_agent import generic_conversation_agent
from agents.snowflake_agents.snowflake_query_agent import snowflake_agent
from utils.snowflake_env import clean_snowflake_query

# Third-party imports
from dotenv import load_dotenv

# -----------------------------------------------------------------------------
# SECTION: Logger Setup
# ----------------------------------------------------------------------------- 

# Get a logger instance for this module
logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------------
# SECTION: Environment Setup
# ----------------------------------------------------------------------------- 

# Load environment variables from .env file
load_dotenv()

# Maximum length of conversation history (message list items) before summarization
# Minimum 1 so "0" in env does not trigger summarization on every turn (summary agent format mismatch)
MAXIMUM_CONVERSATION_HISTORY_LENGTH = max(1, int(os.getenv("MAXIMUM_CONVERSATION_HISTORY_LENGTH", "50")))

# In-graph summarization is off by default: it often returns non-JSON, breaking the run.
def _env_truthy(name: str) -> bool:
    return (os.getenv(name) or "").strip().lower() in ("1", "true", "yes", "on")

WORKFLOW_ENABLE_CONVERSATION_SUMMARY = _env_truthy("WORKFLOW_ENABLE_CONVERSATION_SUMMARY")

_TASK_DISPATCH = {
    "snowflake_agent": snowflake_agent,
    "human_agent": human_agent,
    "generic_conversation_agent": generic_conversation_agent,
}

# -----------------------------------------------------------------------------
# SECTION: Task Executor Implementation
# ----------------------------------------------------------------------------- 

def _trim_conversation_history(conversation_history: Any, max_messages: int = 8) -> list:
    """Trim conversation history to the last N messages and compact fields."""
    if not isinstance(conversation_history, list):
        return []
    # Prefer to keep the last user turns; assistant blobs often use `content` not `user_input`.
    trimmed = conversation_history[-max_messages:]
    normalized = []
    for item in trimmed:
        if isinstance(item, dict):
            role = (item.get("role") or "user").lower()
            if role == "assistant":
                u = (item.get("content") or item.get("user_input") or "")[:5000]
            else:
                u = item.get("user_input") or item.get("content") or ""
            normalized.append({
                "user_input": u,
                "role": "assistant" if role == "assistant" else "user",
                "type": item.get("type", "text")
            })
        else:
            normalized.append({"user_input": str(item), "role": "user", "type": "text"})
    return normalized


def _task_as_dict(task: Any) -> Dict[str, Any]:
    if isinstance(task, dict):
        return task
    if hasattr(task, "model_dump"):
        return task.model_dump()
    if hasattr(task, "dict"):
        return task.dict()
    raise TypeError(f"Unexpected task type: {type(task)!r}")


def _normalize_supervisor_tasks(ai_tasks_list: Any) -> list:
    if ai_tasks_list is None:
        return []
    raw = ai_tasks_list
    if hasattr(raw, "model_dump") and not isinstance(raw, dict):
        raw = raw.model_dump()
    elif hasattr(raw, "dict") and not isinstance(raw, dict):
        raw = raw.dict()
    if isinstance(raw, dict):
        if "tasks" not in raw:
            logger.error("Supervisor output dict missing 'tasks': keys=%s", list(raw.keys()))
            return []
        raw = raw["tasks"]
    if not isinstance(raw, list):
        logger.error("Supervisor tasks not a list: %s", type(raw).__name__)
        return []
    out: list = []
    for t in raw:
        try:
            out.append(_task_as_dict(t))
        except TypeError as e:
            logger.error("%s", e)
    return out


def execute_tasks(ai_tasks_list):
    """
    Executes the list of tasks generated by the supervisor agent, handles dependency resolution,
    and updates task outputs and token counts.
    Args:
        ai_tasks_list (list): List of tasks generated by the supervisor agent.
    Returns:
        tuple: (task_outputs, total_input_tokens_count, total_output_tokens_count, generated_snowflake_queries_list)
    """
    task_outputs = []  # List to store task outputs with sequence IDs
    total_input_tokens_count = 0
    total_output_tokens_count = 0
    generated_snowflake_queries_list = []

    tasks_iter = _normalize_supervisor_tasks(ai_tasks_list)
    for i, task in enumerate(tasks_iter, start=1):  # Start sequence from 1
        function_name = task["function_name"]
        function_params = task["function_params"]
        task_id = i  # Use sequence number as task ID

        # Resolve dependencies if any
        if task.get("depends_on"):
            dep_idx = int(task["depends_on"]) - 1
            if 0 <= dep_idx < len(task_outputs):
                dependent_task_output = task_outputs[dep_idx]["output"]
            else:
                logger.warning(
                    "depends_on=%s out of range (have %s task outputs); using empty prior output",
                    task["depends_on"],
                    len(task_outputs),
                )
                dependent_task_output = ""
            next_task_info = {"function_params": function_params}
            function_params, input_tokens_count, output_tokens_count = dependency_resolver(
                dependent_task_output,
                next_task_info
            )
            total_input_tokens_count += input_tokens_count
            total_output_tokens_count += output_tokens_count
            logger.info("Dependency Resolver Output: %s", function_params)


        func = _TASK_DISPATCH.get(function_name)

        # --- Patch: Ensure snowflake_agent gets a string, not a dict ---
        call_params = function_params
        if function_name == "snowflake_agent":
            # If function_params is a dict with a single string value, extract it
            if isinstance(function_params, dict):
                # Try to extract the first value
                if len(function_params) == 1:
                    call_params = next(iter(function_params.values()))
                else:
                    # If dict has more than one key, fallback to str()
                    call_params = str(function_params)
            elif isinstance(function_params, list) and len(function_params) == 1:
                call_params = function_params[0]

        scratchpad = None  # Default to None to handle different types of outputs
        if func:
            try:
                function_output = func(call_params)

                # Unpack the function output
                if isinstance(function_output, tuple) and len(function_output) == 4:
                    generated_snowflake_query, scratchpad, input_tokens_count, output_tokens_count = function_output
                    # Clean the Snowflake query before storing it
                    if isinstance(generated_snowflake_query, str) and generated_snowflake_query:
                        generated_snowflake_query = clean_snowflake_query(generated_snowflake_query)
                    generated_snowflake_queries_list.append(generated_snowflake_query)
                else:
                    scratchpad, input_tokens_count, output_tokens_count = function_output

                total_input_tokens_count += input_tokens_count
                total_output_tokens_count += output_tokens_count

            except Exception as e:
                scratchpad = f"Error in {function_name}: {str(e)}"
                logger.error(f"Error executing {function_name}: {e}")
        else:
            scratchpad = f"Function '{function_name}' not found."
            logger.error("Unknown task function_name=%r (expected one of %s)", function_name, sorted(_TASK_DISPATCH))

        # Only store task output if it is non-empty
        if scratchpad not in (None, "", [], {}, ()) and bool(scratchpad):
            task_outputs.append({
                "task_id": task_id,
                "function_name": function_name,
                "output": scratchpad
            })

            logger.info("Task done id=%s agent=%s", task_id, function_name)

    return task_outputs, total_input_tokens_count, total_output_tokens_count, generated_snowflake_queries_list

# -----------------------------------------------------------------------------
# SECTION: Workflow Graph Implementation
# ----------------------------------------------------------------------------- 

_BRIEF_RE = re.compile(
    r"\b(short|brief|briefly|concise|succinct|tl;dr|tldr|in one line|one sentence|"
    r"one-line|be quick|just the answer|minimal)\b",
    re.I,
)


def _normalize_response_style(
    user_input: str, explicit: Optional[str] = None
) -> Optional[str]:
    if explicit is not None and str(explicit).strip() != "":
        key = str(explicit).strip().lower()
        if key in ("brief", "short", "minimal"):
            return "brief"
        return None
    if user_input and _BRIEF_RE.search(user_input):
        return "brief"
    return None


def ask_ellis_workflow_graph(
    user_input: str,
    conversation_history: Any,
    chat_id: str | None = None,
    response_style: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Execute the Ask Ellis workflow graph, managing conversation history and invoking various agents.

    Includes retry logic to handle unsatisfactory responses by rerouting tasks through the supervisor with adjustments.

    Args:
        user_input (str): The user's input query.
        conversation_history (Any): The history of the conversation.

    Returns:
        Dict[str, Any]: A dictionary containing the conversation details, total input tokens,
                        and total output tokens used during the execution.
    """

    try:
        # Initialize token counts and retry counters
        total_input_tokens_count = 0
        total_output_tokens_count = 0

        # Initialize conversation and task outputs
        # Trim conversation history before processing to avoid token overflow
        trimmed_conversation_history = _trim_conversation_history(conversation_history, max_messages=8)
        conversation = {
            "conversation_history": trimmed_conversation_history,
            "present_conversation": []
        }
        logger.info("ask_ellis_workflow_graph: user_input=%s history_length=%s", user_input, len(trimmed_conversation_history))
        conversation["present_conversation"].append({"user_input": user_input})

        logger.info("Invoking supervisor agent")

        # Step 1: Generate tasks using the supervisor agent, including retry context
        ai_tasks_list, input_tokens_count, output_tokens_count = supervisor_agent(
            user_input,
            trimmed_conversation_history,
            retry_context=[]  # Pass feedback on what went wrong in previous attempts
        )
        total_input_tokens_count += input_tokens_count
        total_output_tokens_count += output_tokens_count

        # Guard against supervisor failures (e.g., OpenAI auth/timeout) returning error dict
        if isinstance(ai_tasks_list, dict) and ai_tasks_list.get("error"):
            raise RuntimeError(f"Supervisor error: {ai_tasks_list.get('error')}")

        logger.info("Supervisor tasks: %s", ai_tasks_list)

        # Step 2: Execute tasks using the execute_tasks function
        task_outputs, input_tokens_count, output_tokens_count, generated_snowflake_queries_list = execute_tasks(ai_tasks_list)
        total_input_tokens_count += input_tokens_count
        total_output_tokens_count += output_tokens_count

        # Append task outputs to the present conversation
        conversation["present_conversation"].extend(
            [{task["function_name"]: task["output"]} for task in task_outputs]
        )

        logger.info("Invoking Q&A agent")

        # Final call to Q&A agent with agents' responses
        hist_str = (
            json.dumps(trimmed_conversation_history, ensure_ascii=False)[:25000]
            if trimmed_conversation_history
            else "[]"
        )
        style = _normalize_response_style(user_input or "", response_style)
        ellis_response, input_tokens_count, output_tokens_count = q_and_a_agent(
            user_input=user_input,
            agents_response=task_outputs,
            conversation_history=hist_str,
            response_style=style,
        )
        total_input_tokens_count += input_tokens_count
        total_output_tokens_count += output_tokens_count
        conversation["present_conversation"].append({"ellis_response": ellis_response})

        # Additional step to handle conversation history if it exceeds max length
        if (
            WORKFLOW_ENABLE_CONVERSATION_SUMMARY
            and len(conversation["conversation_history"]) > MAXIMUM_CONVERSATION_HISTORY_LENGTH
        ):
            try:
                conversation_summary, input_tokens_count, output_tokens_count = (
                    conversation_summary_agent(
                        conversation_history=conversation["conversation_history"]
                    )
                )
                total_input_tokens_count += input_tokens_count
                total_output_tokens_count += output_tokens_count
                conversation["conversation_history"].clear()
                conversation["conversation_history"].append(
                    {"conversation_summary": conversation_summary}
                )
            except Exception as e:
                logger.warning("Conversation summary step skipped: %s", e)

        # present_conversation is a flat list of dicts; extend so history stays a list of message dicts
        conversation["conversation_history"].extend(conversation["present_conversation"])

        # Return final conversation details and token counts
        out: Dict[str, Any] = {
            "conversation": conversation,
            "generated_snowflake_query": generated_snowflake_queries_list,
            "input_tokens_count": total_input_tokens_count,
            "output_tokens_count": total_output_tokens_count,
        }
        if chat_id:
            out["chat_id"] = chat_id
        return out

    except Exception as e:
        logger.exception("Error in ask_ellis_workflow_graph: %s", e)
        err_body: Dict[str, Any] = {
            "conversation": {
                "conversation_history": trimmed_conversation_history if 'trimmed_conversation_history' in locals() else [],
                "present_conversation": [{"user_input": user_input, "error": str(e)}],
                "error": str(e)
            },
            "generated_snowflake_query": [],
            "input_tokens_count": total_input_tokens_count if 'total_input_tokens_count' in locals() else 0,
            "output_tokens_count": total_output_tokens_count if 'total_output_tokens_count' in locals() else 0,
            "error": "ask_ellis_workflow_graph failed: %s" % str(e)
        }
        if chat_id:
            err_body["chat_id"] = chat_id
        return err_body

# -----------------------------------------------------------------------------
# END OF MODULE
# ----------------------------------------------------------------------------- 
