"""
Module Name: snowflake_connector.py
 
Description:
This module provides functionality to execute SQL queries on a Snowflake database.
It handles the connection setup using environment variables, execution of SQL queries,
and returning results in JSON format. Errors are handled and returned as JSON strings
to ensure robustness.
 
"""
 
# -----------------------------------------------------------------------------
# SECTION: Imports
# -----------------------------------------------------------------------------
 
# Standard library imports
from typing import Dict, Any
import logging
import json
import os
import re
 
# Third-party imports
from dotenv import load_dotenv
import snowflake.connector
 
# -----------------------------------------------------------------------------
# SECTION: Logger Setup
# -----------------------------------------------------------------------------
 
# Get a logger instance for this module
logger = logging.getLogger(__name__)
 
# -----------------------------------------------------------------------------
# SECTION: Environment Variable Loading
# -----------------------------------------------------------------------------
 
# Load environment variables from the .env file
load_dotenv()
 
# Retrieve environment variables
SF_USER = os.getenv("SF_USER")
SF_PASSWORD = os.getenv("SF_PASSWORD")
SF_ACCOUNT = os.getenv("SF_ACCOUNT")
SF_DATABASE = os.getenv("SF_DATABASE")
SF_WAREHOUSE = os.getenv("SF_WAREHOUSE")
SF_ROLE = os.getenv("SF_ROLE")
 
# -----------------------------------------------------------------------------
# SECTION: Clean unwanted Double Quotes from LLM-Generated SQL Queries
# -----------------------------------------------------------------------------
 
def clean_snowflake_query(query: str) -> str:
    """
    Clean unwanted double quotes from an LLM-generated SQL query while keeping
    double quotes around identifiers with special characters.
 
    Args:
        query (str): The SQL query generated by the LLM.
 
    Returns:
        str: The cleaned and executable SQL query.
    """
    # Step 1: Remove double quotes around standard identifiers but retain them for those with special characters
    # Retain quotes around identifiers with non-alphanumeric characters
    cleaned_query = re.sub(r'\"([a-zA-Z0-9_]+)\"', r'\1', query)
 
    # Step 2: Replace multiple spaces/newlines with a single space
    cleaned_query = re.sub(r'\s+', ' ', cleaned_query)
 
    # Step 3: Trim leading and trailing spaces
    cleaned_query = cleaned_query.strip()
 
    return cleaned_query
 
 
# -----------------------------------------------------------------------------
# SECTION: Executing SQL query on Snowflake DB
# -----------------------------------------------------------------------------
 
def execute_snowflake_query(sql_query: str) -> str:
    """
    Execute a SQL query on Snowflake and return the result as a JSON string.
 
    Args:
        sql_query (str): The SQL query to execute.
 
    Returns:
        str: A JSON string representing the query result, or an error message if
        the query execution fails.
    """
    connection_params: Dict[str, Any] = {
        "user": "SIDDHU",
        "password": "NagaSiddhard@159",
        "account": "cjzlrgx.ap-south-1.aws",
        "warehouse": "COMPUTE_WH",
        "database": "SNOWFLAKE_SAMPLE_DATA",
        "role": "TPCH_SF1",
    }
 
    conn = None
    cur = None
 
    try:
        # Establish a connection to Snowflake
        conn = snowflake.connector.connect(**connection_params)
 
        # Create a cursor object
        cur = conn.cursor()
 
        # Execute the query and fetch the results
        cur.execute(clean_snowflake_query(sql_query))
        column_names = [metadata.name for metadata in cur.description]
        rows = cur.fetchall()
 
        # Convert the results to JSON format
        json_data = json.dumps([
            {key: str(value) for key, value in zip(column_names, row)}
            for row in rows
        ])
        return json_data
 
    except snowflake.connector.errors.ProgrammingError as pe:
        logger.error(pe)
        return json.dumps({"error": str(pe)})
 
    except snowflake.connector.errors.DatabaseError as de:
        logger.error(de)
        return json.dumps({"error": f"Snowflake Database Error: {de}"})
 
    except Exception as e:
        logger.error(e)
        return json.dumps({"error": f"An unexpected error occurred: {e}"})
 
    finally:
        # Ensure the cursor is closed
        if cur:
            try:
                cur.close()
            except Exception:
                pass
 
        # Ensure the connection is closed
        if conn:
            try:
                conn.close()
            except Exception:
                pass
 
# -----------------------------------------------------------------------------
# END OF MODULE
# -----------------------------------------------------------------------------